### ISSUE TITLE
Security issue? problematic defaults for hashlib.pbkdf2_hmac

### ISSUE THREAD

**Issue by oz123** [FedericoCeratto/bottle-cork#112]
Currently, cork uses hard coded options for this:

```
h = hashlib.pbkdf2_hmac('sha1', cleartext, salt, 10, dklen=32)
```

As far as I understand (disclaimer, I am not a crypto expert...) this are too low default.
This should be updated to sha256 and 10000 iterators, or at least updated such that the programmer
using cork, can easily change it.

See discussions here:

http://security.stackexchange.com/questions/3959/recommended-of-iterations-when-using-pkbdf2-sha256
https://cryptosense.com/parameter-choice-for-pbkdf2/

And Python's own docs:

> The number of iterations should be chosen based on the hash algorithm and computing power. As of 2013, at least 100,000 iterations of SHA-256 are suggested.

https://docs.python.org/3/library/hashlib.html#module-hashlib

**Comment by FedericoCeratto** [comment]
Thanks for the bug report. With the current fix, users can select algorith and iterations.
