### ISSUE TITLE
Registration does not check pending_registrations collection for existence of the user name

### ISSUE THREAD

**Issue by equalogix** [FedericoCeratto/bottle-cork#113]
The registration method does not do a check to determine the existence of the username in the pending_registration collection (table). So two users could request the use of the same username  provided that neither user has confirmed the registration.  Both users would receive a confirmation email. Then the first user to confirm will "block" the Users collection, thus causing an error when the second user attempts to confirm registration.

A second case would be where a user resubmits the registration form twice but does not confirm the registration between submits. If the user uses the same password and email it shouldn't cause a problem. But otherwise it could cause future confusion.

I have implemented a stop gap measure, by creating a unique index on the Username field of the pending_registrations collection. Then when the situation arises I catch the duplicate entry error from Mongo-db in my bottle/app code and notify the user that the name is taken. But this does not prevent the registration method from sending the notification email to user.

This check needs to be done in the registration method and raise the UserExists error as is the case when the username is already taken in the Users collection.

I'm using Bottle and Cork with the MongoDB backend.

**Comment by equalogix** [comment]
I found a better and more obvious solution for the work around. Before calling the registration method in the Bottle/app, I do a find_one for the username in the pending_registrations collection. If it returns None, I then call the registration method.  This step should be included in the registration method itself.

Given the low likelihood of the occurrence of this situation it may be preferable to simply try the update of the pending_registrations collection and then handle the duplicate key error if it occurs.

**Comment by FedericoCeratto** [comment]
Thanks for the feedback @equalogix
Unfortunately handling registrations have some tricky tradeoffs, as the registration method can be exposed to spam robots & co that can try to register large numbers of common names.
If you block duplicate registrations legitimate users can be prevented from registering by bots. Also, users might lose the first email or want to switch to a different email address before validating the registration.
Either the registration or the registration-validation have to work as "first comes first serve" to get a login. The latter seems safer as it requires a working email address.

**Comment by equalogix** [comment]
Federico, thank you for the quick reply.

I see your perspective, and all your points are valid. In terms of spam bots, I think there are more effective ways of dealing with the problem. The issue is that these measures are still required since with the current design a spam bot could still overload your db with pending registrations. One feature that you may want to consider would be adding is a TTL (time to live) index on the pending_registrations, such that records will be deleted after say 24 hours.

I think you are absolutely right when you say there are many trade-offs. In a Utopian world, the package would be agnostic in terms of these trade-offs and it would be up to the app designer to structure the app in way that is optimal for its specific needs. But we do not live in a Utopian world.

Nick

**Comment by FedericoCeratto** [comment]
`_purge_expired_registrations` does what you are asking for - the default time value is 96 hours - but it's not being run automatically (and maybe it should?).

> the package would be agnostic in terms of these trade-offs and it would be up to the app designer to structure the app in way that is optimal for its specific needs

That's what you've done with find_one on pending_registrations - maybe it's a matter of documenting this use-cases. (contributions are welcome :) )
