### ISSUE TITLE
Email Not Sent - Auth Error

### ISSUE THREAD

**Issue by colourdelete** [FedericoCeratto/bottle-cork#121]
When I try to signup, It goes to the code validation screen, but the following error is there and I don't get the email

### Output

![image](https://user-images.githubusercontent.com/45807097/58461439-a407c580-816a-11e9-8d70-3829cc548069.png)

(Sorry clipboard didn't work)

**Comment by colourdelete** [comment]
Whole source code is available at: https://gitlab.com/colourdelete/kagi
[kagi-master.zip](https://github.com/FedericoCeratto/bottle-cork/files/3228250/kagi-master.zip)

**Comment by FedericoCeratto** [comment]
@colourdelete the 2 files are empty. What smtp url are you using?

**Comment by nyiyui** [comment]
I'm using Gmail.
`auth = Cork(directory='cork', smtp_url='smtp://tanjunkagi:PASSWORD@smtp.gmail.com:587', email_sender="tanjunkagi@gmail.com")`
Sorry for the late reply.

**Comment by nyiyui** [comment]
I looked at similar issues, and I realized that they used STARTTLS and a applicaion-specific password. Maybe this is it?

**Comment by nyiyui** [comment]
Using STARTTLS and turning on setting "Less secure app access" did the trick, but 404 at email validation page. WIll make a new issue for that.

**Comment by nyiyui** [comment]
Forgot to click "Close and commit" button.
