### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/bottle-cork#4]

**Comment by oshihirii** [comment]
Hello, 

I'm looking at [Python 3 Wall of Superpowers](https://python3wos.appspot.com) which shows `Bottle` and `Beaker`have `Python 3` compatibility - specifically [bottle 0.12.8 is compatible with Python 3.3](https://pypi.python.org/pypi/bottle/0.12.8) and [Beaker 1.6.4 is compatible with Python 3.2](https://pypi.python.org/pypi/Beaker).  

Does this change things at all and make `Cork` compatible with Python 3? 

Thank You.

**Comment by FedericoCeratto** [comment]
Bottle is indeed compatible with Python 3 while Beaker is still not entirely compatible (see bug listed above). Beaker has not been maintained since 2013 and the last release is from 2012.
Moving away from it seems to be the only option at this point.

**Comment by oshihirii** [comment]
Ok, thank you for the information, I would contribute time to look into it, but the operations of Beaker are a little out of my league I think.  I will watch this topic with interest.

**Comment by FedericoCeratto** [comment]
Good news, @amol- is taking over Beaker and released a new version already:
https://github.com/bbangert/beaker/commits/master

**Comment by oshihirii** [comment]
Wow, thanks for the update.  So is Beaker compatible with Python 3 yet, or still on the horizon?

**Comment by amol-** [comment]
Beaker 1.6 is compatible with some versions of PY3, see that on travis is already tested again 3.2: https://travis-ci.org/bbangert/beaker/builds/49749936

Support for PY3 in 1.6.5 is currently achieved using 2to3 and some fixes during installation, I worked on a fully native solution which is currently tested against all py3.2, py3.3, py3.4 https://travis-ci.org/TurboGears/beaker

The fully native solution will be released as soon as I have time to merge it back into the main trunk and test it on some real world project, in the mean while you can freely clone it from https://github.com/TurboGears/beaker and send feedbacks if you find any issue.

**Comment by FedericoCeratto** [comment]
@oshihirii and @amol- the main blocker that is currently preventing Cork to use Beaker with python3 is bbangert/beaker#21 , which is still unpatched.

**Comment by FedericoCeratto** [comment]
Added patch bbangert/beaker/pull/75

**Comment by FedericoCeratto** [comment]
Beaker v1.7.0dev was released 19 days ago. Pending release of a stable version.

**Comment by glebourgeois** [comment]
not out yet ?

**Comment by FedericoCeratto** [comment]
Nope, the last activity from was releasing the dev version on 25 Feb.
@amol- : any plan to release a stable version soon? Thanks!

**Comment by amol-** [comment]
@FedericoCeratto no plans, waiting a reasonable span of time to confirm no major bugs have been introduced due to the rewrite. The changes were big so I need to confirm third party projects continue to work as before.

**Comment by FedericoCeratto** [comment]
@amol-: thanks for the reply. I'll import the dev version and test Cork on Python 3 against it.

**Comment by amol-** [comment]
@FedericoCeratto any feedback on testing beaker with Cork on py3? I plan to release Beaker as stable in a few days but wanted to wait for Cork feedback :)

**Comment by FedericoCeratto** [comment]
@amol-: I'm currently testing the new version and seems to be working. I'll publish the updated unit tests shortly.

**Comment by FedericoCeratto** [comment]
@amol- crypto.generateCryptoKeys(cleartext, salt, 10) is generating different hash values under python2.7 and python3.4 with Beaker 1.7 - is this expected?

**Comment by amol-** [comment]
It might yes, when hashlib.pbkdf2_hmac is available that is used otherwise a builtin pbkdf2 implementation is used. You can check on both interpreter with `hasattr(hashlib, "pbkdf2_hmac")` if the two provide different answers they will probably lead to different keys.

**Comment by FedericoCeratto** [comment]
@amol-: I suspect this is the culprit: https://github.com/bbangert/beaker/issues/81

**Comment by amol-** [comment]
@FedericoCeratto fixed bbangert/beaker#81
Should I proceed with release or did you find any other issue?

**Comment by FedericoCeratto** [comment]
@amol- I haven't found anything else so far.

**Comment by FedericoCeratto** [comment]
Version 0.12.0a1 released with Python 3 support.

**Comment by FedericoCeratto** [comment]
Version 0.12.0a2 released
