### ISSUE TITLE
IndentationError: ('expected an indented block', ('/usr/local/lib/python2.7/dist-packages/cork/sessions.py', 15, 8, '    json()\n'))

### ISSUE THREAD

**Issue by snvandoorn** [FedericoCeratto/bottle-cork#80]
When calling 
sudo pip install bottle-cork
 
I get the error message in the installation process:
Installing collected packages: bottle-cork, Beaker, pycrypto
  Running setup.py install for bottle-cork
    Sorry: IndentationError: ('expected an indented block', ('/usr/local/lib/python2.7/dist-packages/cork/sessions.py', 15, 8, '    json()\n'))

I am not sure what the effect of it is, as the total installation was commented to be succesful

**Comment by snvandoorn** [comment]
As a result cork could not be used: the example with decorator resulted in the following issue, also after correcting the sessions.py indentation issue:
pi@yyyyy:~$ python cork.py
Traceback (most recent call last):
  File "cork.py", line 13, in <module>
    from cork import Cork
  File "/home/pi/cork.py", line 13, in <module>
    from cork import Cork
ImportError: cannot import name Cork

**Comment by FedericoCeratto** [comment]
Can you reproduce the bug in a virtualenv? This works for me:

    virtualenv . && . bin/activate && pip install -v bottle-cork

**Comment by snvandoorn** [comment]
As said, calling "sudo pip install bottle-cork" had this issue and I could verify that the respective call was not sufficinely indented. No need to use a virtualenv.

**Comment by FedericoCeratto** [comment]
Without further details I cannot troubleshoot the issue. Can you run commands above? And, if successful, include the versions of Python, Bottle and Cork?
