### ISSUE TITLE
Unicode characters in usernames 

### ISSUE THREAD

**Issue by jsve** [FedericoCeratto/bottle-cork#81]
Usernames (and perhaps also passwords) cannot have unicode characters. This would be great for users with Scandinavian letters in their names (like å ä ö æ ö).

**Comment by FedericoCeratto** [comment]
@jsve: hi, can you test the latest code change?

**Comment by jsve** [comment]
Seems to be working. I was using the SQLite backend, but this seems to be out of date on several areas. Tried to update it, but without luck... Changed to SQLAlchemy and unicode is working fine now!
