### ISSUE TITLE
webpage virtualenv suggestion provides conflicting rationale

### ISSUE THREAD

**Issue by atehwa** [FedericoCeratto/bottle-cork#89]
On the Cork main page (http://cork.firelet.net), there is an item like this:

"Use virtualenv on package-based Linux distributions! Learn why"

Now, unlike this short summary suggests, the linked page does _not_ propose virtualenv as the primary solution but as a secondary solution:

"If you do not like to bring your system to "unstable" and still want to run Pylons applications you can create a virtual environment (virtualenv).[...] The drawback is that you do not get security updated from "apt" so you are completely on your own."

So, maybe you should also change the recommendation to using packaged modules, and only if that is not an option, to use virtualenv.

**Comment by FedericoCeratto** [comment]
There are no packaged version for the major distributions at the moment - otherwise I would be very happy to recommend it as the default option.
