### ISSUE TITLE
installed using pip. but not working. (python3)

### ISSUE THREAD

**Issue by jviyer** [FedericoCeratto/bottle-cork#94]
at first python3 import did not work. then somewhere saw a comment about changing it 
to from cork.cork import Cork in __init__.py. 
did that and still get this error
Does it work in python 3? 

Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cork
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jv/.virtualenvs/tai0/lib/python3.4/site-packages/cork/__init__.py", line 7, in <module>
    from cork.cork import Cork, JsonBackend, AAAException, AuthException, Mailer, FlaskCork, Redirect
  File "/home/jv/.virtualenvs/tai0/lib/python3.4/site-packages/cork/cork.py", line 40, in <module>
    from backends import JsonBackend
ImportError: No module named 'backends'

**Comment by team-python** [comment]
No answer?  Does this suggest 'no', python 3 is not supported yet?

**Comment by FedericoCeratto** [comment]
Python 3 is supported. Can you please try reproducing the bug from the sources on GitHub? Thanks!

**Comment by jnturton** [comment]
@team-python, @jviyer: pip pulled down a pre-Python 3 version for me.  I downloaded and installed from GitHub and things started working.

@FedericoCeratto: your examples are still not ported to Python 3 however (`bottle-cork-0.12.0a2.tar.gz`)

**Comment by FedericoCeratto** [comment]
Fixed in the latest release 0.12.0 on PyPI
