### ISSUE TITLE
is anyone has idea about this  ? 

### ISSUE THREAD

**Issue by lifecoder1988** [FedericoCeratto/bottle-cork#95]
'hash': cork._hash(username, password),
  File "build/bdist.linux-x86_64/egg/cork/cork.py", line 602, in _hash
  File "build/bdist.linux-x86_64/egg/cork/cork.py", line 652, in _hash_pbkdf2
AttributeError: 'module' object has no attribute 'pbkdf2_hmac'

**Comment by FedericoCeratto** [comment]
Are you using Python >= 2.7.8? pbkdf2_hmac has been added in that version.

**Comment by lifecoder1988** [comment]
yes  i have fix the problem by using the lower version . :)

**Comment by swill** [comment]
I don't think this problem is solved.

I am getting `'module' object has no attribute 'pbkdf2_hmac'` when trying to do a `aaa.create_user(...)`.

I am using `Python 2.7.9` and the `MongoDBBackend` with `pymongo==2.8`.

Any suggestions would be helpful...

**Comment by swill** [comment]
Here is the full trackback:
`Traceback (most recent call last):
  File "./server.py", line 212, in create_user
    aaa.create_user(posted('username'), posted('role'), posted('password'), posted('email'))
  File "/usr/local/lib/python2.7/site-packages/cork/cork.py", line 308, in create_user
    h = self._hash(username, password)
  File "/usr/local/lib/python2.7/site-packages/cork/cork.py", line 616, in _hash
    return self._hash_pbkdf2(username, pwd, salt=salt)
  File "/usr/local/lib/python2.7/site-packages/cork/cork.py", line 666, in _hash_pbkdf2
    h = hashlib.pbkdf2_hmac('sha1', cleartext, salt, 10, dklen=32)
AttributeError: 'module' object has no attribute 'pbkdf2_hmac'`

**Comment by swill** [comment]
I uninstalled `hashlib` and reinstalled it and that seemed to fix the problem.  The version did not change, so it was just the reinstall that fixed it.  I am using this version of hashlib: `hashlib==20081119`

**Comment by deltaflyer** [comment]
The problem is caused by following fact. The function pbkdf2_hmac was introduced with Python 2.7.8. If you are using an older version of Python 2.7.8 you'll get the error. This problem occurs on Ubuntu 14.04.3 LTS Server, as they ship Python 2.7.6 by default, which does not include  pbkdf2_hmac.

**Comment by yamsu** [comment]
For those still using Ubuntu 14.04 LTS pbkdf2_hmac is available in backports.pbkdf2 
minor changes in the cork.py can be made to import that from the above package as opposed to the hashlib.

`
if sys.version_info[0:3] < (2, 7, 8):
    print("Python >= 2.7.8 is required")
    # sys.exit(1)
    from backports.pbkdf2 import pbkdf2_hmac, compare_digest
else:
    from hashlib import pbkdf2_hmac
`
In _hash_pbkdf2 function make the following change.

`
 h = pbkdf2_hmac('sha1', cleartext, salt, 10, dklen=32)
`
