### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by bantonj** [FedericoCeratto/bottle-cork#96]
I have a site that is using the SqlAlchemyBackend and when the site is not accessed for 8 hours I get this error. 

`OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT roles.role \nFROM roles \nWHERE roles.role = %s'] [parameters: ('user',)]`

**Comment by bantonj** [comment]
I tested out using SQLAlchemy's recommended fix for this issue, using the `pool_recycle=3600` option. That seems to have fixed the issue.

http://docs.sqlalchemy.org/en/rel_0_8/dialects/mysql.html#mysql-connection-timeouts

**Comment by FedericoCeratto** [comment]
Thanks for the PR, it's committed.
